package ubb.scs.socialnetworkgui.utils.events;

public enum ChangeEventType {
    ADD,UPDATE,DELETE,
    FRIEND_REQUEST_SEND, FRIEND_REQUEST_ACCEPT, FRIEND_REQUEST_REJECT,
    FRIENDSHIP_ADD, FRIENDSHIP_DELETE,
    MESSAGE_SENT, MESSAGE_RECEIVE;
}
